name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: aniven/xoyeb
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
